-- CAR_RENTAL_COMPANY_CAR 테이블: CAR_ID, CAR_TYPE, DAILY_FEE, OPTIONS
-- CAR_TYPE: 세단, SUV, 승합차, 트럭, 리무진
-- OPTIONS: 주차감지센서, 스마트키, 네비게이션, 통풍시트, 열선시트, 후방카메라, 가죽시트 (콤마로 구분)

-- CAR_RENTAL_COMPANY_RENTAL_HISTORY 테이블: HISTORY_ID, CAR_ID, START_DATE, END_DATE

-- CAR_RENTAL_COMPANY_DISCOUNT_PLAN 테이블: PLAN_ID, CAR_TYPE, DURATION_TYPE, DISCOUNT_RATE
-- DURATION_TYPE: 7일 이상, 30일 이상, 90일 이상 (7일 미만은 할인 정책 없음)


-- 자동차 종류가 '세단' 또는 'SUV' 인 자동차 중 2022년 11월 1일부터 2022년 11월 30일까지 대여 가능하고 30일간의 대여 금액이 50만원 이상 200만원 미만인 자동차에 대해서 자동차 ID, 자동차 종류, 대여 금액(컬럼명: FEE) 리스트를 출력하는 SQL문을 작성해주세요. 
-- 결과는 대여 금액을 기준으로 내림차순 정렬, 금액이 같은 경우 자동차 종류를 기준으로 오름차순 정렬, 자동차 종류까지 같은 경우 자동차 ID를 기준으로 내림차순 정렬

SELECT CAR_ID, CAR_TYPE, DAILY_FEE*30*(100-DISCOUNT)*0.01 AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
JOIN (
    SELECT DISTINCT CAR_ID AS RENTALED_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE CAR_ID NOT IN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE START_DATE <= 20221130 AND END_DATE >= 20221101
    )
) H
ON C.CAR_ID=H.RENTALED_ID
JOIN (
    SELECT CAR_TYPE AS CAR, DISCOUNT_RATE AS DISCOUNT
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE (CAR_TYPE = '세단' OR CAR_TYPE = 'SUV') AND DURATION_TYPE = '30일 이상'
) D
ON C.CAR_TYPE = D.CAR
WHERE CAR_TYPE IN ('세단', 'SUV') AND DAILY_FEE*30*(100-DISCOUNT)*0.01 >= 500000 AND DAILY_FEE*30*(100-DISCOUNT)*0.01 < 2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC
